# Use an official Maven image as the base image
FROM maven:3.8.4-openjdk-11-slim AS build
# Copy the pom.xml and the project files to the container
COPY pom.xml .
COPY src ./src
# Build the application using Maven
RUN mvn clean package -DskipTests
# Use an official OpenJDK image as the base image
FROM openjdk:11-jre-slim
COPY target/sb-webapp.jar .
CMD ["java","-jar" , "sb-webapp.jar"]
